// src/app/layout.tsx
import { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/authContext";
import Navbar from "@/components/Navbar"; // Ensure Navbar is a Client Component

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {/* Ensure Navbar is already a client component */}
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}